"""create_user_social_accounts_table

Revision ID: 49172a6ca10d
Revises: 14f85a4b19a5
Create Date: 2024-06-04 23:48:44.787300

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49172a6ca10d"
down_revision: Union[str, None] = "14f85a4b19a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_social_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(255), nullable=False),
        sa.Column(
            "provider_user_id", sqlmodel.sql.sqltypes.AutoString(255), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_social_accounts_user_id"),
        "user_social_accounts",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_social_accounts_user_id"), table_name="user_social_accounts"
    )
    op.drop_table("user_social_accounts")
    # ### end Alembic commands ###
