version: "3"

volumes:
  fastapi-tutorial-db-volume:

services:
  fastapi-tutorial-app:
    container_name: fastapi-tutorial-app
    build: .
    restart: always
    command: uvicorn src.main:app --port 8000 --host 0.0.0.0 --reload
    volumes:
      - .:/src
    ports:
      - 8099:8000

  fastapi-tutorial-db:
    container_name: fastapi-tutorial-db
    build: ./docker/postgres
    ports:
      - "5432:5432"
    volumes:
      - fastapi-tutorial-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: fastapi-tutorial
