version: "3"

volumes:
  fastapi-tutorial-db-volume:

services:
  fastapi-tutorial-app:
    container_name: fastapi-tutorial-app
    build: .
    restart: always
    command: uvicorn src.main:app --port 8000 --host 0.0.0.0 --reload
    volumes:
      - .:/src
    ports:
      - 8099:8000

  fastapi-tutorial-db:
    container_name: fastapi-tutorial-db
    build: ./docker/mysql
    ports:
      - "3309:3306"
    volumes:
      - fastapi-tutorial-db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fastapi-tutorial
